/* Valid five-letter words for Word Quest — used both as the answer pool
   and to validate guesses (so only real words are accepted).
   Anything that isn't exactly five letters a–z is dropped on load, so
   stray tokens can never break the game. */

const RAW =
  "about above abuse actor acute admit adopt adult after again agent agree ahead alarm album " +
  "alert alike alive allow alone along alter amber amend among ample angel anger angle angry " +
  "ankle apart apple apply arena argue arise armor aroma array arrow aside asset audio audit " +
  "avoid await awake award aware awful badge badly baker basic basin batch beach beard beast " +
  "began begin being belly below bench berry birth black blade blame bland blank blast blaze " +
  "bleak blend bless blind block blond blood bloom blown blunt blurt blush board boast bonus " +
  "boost booth bound brain brake brand brave bread break breed brick bride brief bring brink " +
  "broad broke brood brook broom brown brush brute build built bunch burst cabin cable camel " +
  "candy canoe cargo carry carve catch cause cease chain chair chalk champ chant chaos charm " +
  "chart chase cheap cheat check cheek cheer chess chest chief child chili chill chime china " +
  "chips choir chord chose chunk cider cigar civic civil claim clamp clash clasp class clean " +
  "clear clerk click cliff climb cling cloak clock clone close cloth cloud clout clown club " +
  "clued clump clung coach coast cobra cocoa colon color comet comic coral couch cough could " +
  "count court cover crack craft cramp crane crash crate crawl craze crazy cream creek creep " +
  "crepe crept crest crick crime crisp croak crook cross crowd crown crude cruel crumb crush " +
  "crust crypt cubic curly curry curse curve cycle daily dairy daisy dance dandy datum dealt " +
  "death debit debut decay decor delay delta dense depot depth derby devil diary dimly diner " +
  "dingo dirty disco ditch ditto dizzy dodge doing donor doubt dough dozen draft drain drake " +
  "drama drank drawn dread dream dress dried drift drill drink drive drone drool droop drove " +
  "drown druid drums drunk dryer dwarf dwell dying eager eagle early earth easel eaten ebony " +
  "edict eerie eight elbow elder elect elegy elite elope email ember empty enact ended enemy " +
  "enjoy enter entry equal equip erase error essay ether ethic event every evict evoke exact " +
  "exalt excel exert exile exist extra fable faced facet fairy faith false fancy fatal fault " +
  "favor feast fence ferry fetch fever fewer fiber field fiend fiery fifth fifty fight final " +
  "finch first fishy fixed fizzy flair flame flank flash flask fleck fleet flesh flick flier " +
  "fling flint flirt float flock flood floor flora floss flour flown fluid fluke flung flush " +
  "flute foamy focal focus foggy force forge forte forth forty forum found frame frank fraud " +
  "freak fresh fried frill frock frost frown froze fruit fudge fully fumes funny furry fussy " +
  "gauge gaunt gavel gecko geese genie genre ghost ghoul giant giddy gift girth given giver " +
  "glade gland glare glass gleam glean glide globe gloom glory gloss glove glyph gnome going " +
  "golem goods goose grace grade graft grain grand grant grape graph grasp grass grate grave " +
  "gravy graze great greed green greet grief grill grime grind groan groin groom grope gross " +
  "group grove growl grown gruel gruff grunt guard guess guest guide guild guilt guise gully " +
  "gusto gypsy habit hairy halve handy happy hardy harsh haste hatch haunt haven havoc heart " +
  "heath heave heavy hedge hefty hello hence heron hinge hippo hobby hoist holly homer honey " +
  "honor horde horse hotel hound house hover human humid humor hunch hurry hyena ideal idiom " +
  "idiot image imply inbox incur index inept inert infer ingot inlet inner input inter intro " +
  "ionic irate irony issue ivory jaunt jazzy jelly jewel joint joist jolly joker judge juice " +
  "juicy jumbo jumpy kayak kebab kinky kiosk kitty knack knead kneel knelt knife knock knoll " +
  "known koala label labor laden lance lapse large larva laser latch later layer leach leafy " +
  "leaky leant leapt learn lease leash least leave ledge leech leery lemon level lever light " +
  "lilac limbo limit lined linen liner links liver llama loath lobby local locus lodge lofty " +
  "logic login loose lorry loser lotus louse lousy lover lower loyal lucid lucky lumen lunar " +
  "lunch lunge lurch lurid lying lymph lyric macaw macho macro madam madly magic magma maize " +
  "major maker mango mania manor maple march marsh mason match matey mauve maxim maybe mayor " +
  "meant medal media medic melon mercy merge merit merry messy metal meter metro micro midst " +
  "might mimic mince miner minor minus mirth mixed mocha model modem mogul moist molar moldy " +
  "money month moody moose moral moron motel motif motor motto mound mount mourn mouse mouth " +
  "mover movie mower mucky muddy mulch mummy munch mural murky mushy music musky musty myrrh " +
  "nadir naive nanny nasal nasty naval navel needy neigh nerve never newer newly nicer niche " +
  "niece night ninja ninth noble nobly noise noisy nomad north nosey notch noted novel nudge " +
  "nurse nutty nylon oaken oasis occur ocean octal octet odder offer often olive omega onion " +
  "onset opera optic orbit order organ other otter ought ounce outdo outer ovary overt owing " +
  "owner ozone paced paddy pagan paint panel panic paper parka parry party pasta paste patch " +
  "patio pause payee peace peach pearl pecan pedal penny perch peril perky pesky petal petty " +
  "phase phone photo piano picky piece piety piggy pilot pinch pinky piper pitch pivot pixel " +
  "pizza place plaid plain plane plank plant plate plaza plead pleat plied plot plows pluck " +
  "plumb plume plump plunk plush poach point poise polar polka pooch porch posit pouch pound " +
  "power prank prawn preen press price prick pride pried prime primp print prior prism prize " +
  "probe prone prong proof prose proud prove prowl proxy prude pry psalm pubic pudgy puffy " +
  "pulse punch pupil puppy puree purge purse quack quail quake qualm quark quart quash quasi " +
  "queen queer quell query quest queue quick quiet quill quilt quirk quite quota quote rabid " +
  "racer radar radio rainy raise rajah rally ranch range rapid raspy ratio raven razor reach " +
  "react ready realm rearm rebel rebut recap recur regal rehab reign relax relay relic remit " +
  "renal renew repay repel reply rerun reset resin retro reuse rhino rhyme rider ridge rifle " +
  "right rigid rinse ripen riser risky rival river roach roast robin robot rocky rodeo rogue " +
  "roomy roost rotor rouge rough round rouse route rover royal ruddy ruder rugby ruler rumor " +
  "rural rusty saber sadly safer saint salad sally salon salsa salty salve sandy sappy sassy " +
  "satin sauce saucy sauna saved savor scale scalp scaly scamp scant scare scarf scary scene " +
  "scent scoff scold scoop scope score scorn scour scout scowl scram scrap screw scrub scuba " +
  "seedy seize sense serum serve setup seven sever sewer shack shade shady shaft shake shaky " +
  "shale shall shame shank shape shard share shark sharp shave shawl shear sheen sheep sheer " +
  "sheet shelf shell shied shift shine shiny shire shirk shirt shoal shock shone shook shoot " +
  "shore short shout shove shown showy shrub shrug shuck shunt shush shyly siege sieve sight " +
  "sigma silky silly since sinew singe siren sissy sixth sixty sized skate skier skill skimp " +
  "skirt skull skunk slack slain slang slant slash slate sleek sleep sleet slept slice slick " +
  "slide slime slimy sling slink slope slosh sloth slump slung slurp slush small smart smash " +
  "smear smell smelt smile smirk smite smith smock smoke smoky snack snail snake snaky snare " +
  "sneak sneer snide sniff snipe snoop snore snort snout snowy snuck snuff sober soggy solar " +
  "solid solve sonar sonic sooth sooty sound south space spade spank spare spark spasm spawn " +
  "speak spear speck speed spell spend spent sperm spice spicy spied spike spiky spill spilt " +
  "spine spiny spire spite splat split spoil spoke spook spool spoon spore sport spout spray " +
  "spree sprig spurn spurt squad squat squib stack staff stage staid stain stair stake stale " +
  "stalk stall stamp stand stank stare stark start stash state stave steak steal steam steed " +
  "steel steep steer stein stern stick stiff still stilt sting stink stint stock stoic stoke " +
  "stole stomp stone stony stood stool stoop store stork storm story stout stove strap straw " +
  "stray strip strut stuck study stuff stump stung stunt style suave sugar suite sulky sunny " +
  "super surge swarm swash swath swear sweat sweep sweet swell swept swift swill swine swing " +
  "swirl swish sword swore sworn swung syrup table taboo tacit tacky taffy taken tally talon " +
  "tamer tango tangy taper tapir tardy tarot taste tasty taunt tawny teach tease teddy tempo " +
  "tenor tense tenth tepid terms terse testy thank theft their theme there these thick thief " +
  "thigh thing think third thong thorn those three threw throb throw thumb thump thyme tiara " +
  "tidal tiger tight tilde timer times timid tipsy titan tithe title toast today token tonal " +
  "tonic tooth topaz topic torch total touch tough towel tower toxic toxin trace track tract " +
  "trade trail train trait tramp trash tread treat trend triad trial tribe trick tried tries " +
  "tripe trite troll troop trope trout trove truce truck truly trump trunk truss trust truth " +
  "tryst tuber tulip tumor tunic turbo tutor twang tweak tweed tweet twice twine twirl twist " +
  "ulcer ultra umbra uncle under undue unfit union unite unity unmet until upper upset urban " +
  "usage usher usual usurp utter vague valet valid value valve vapor vault vaunt vegan venom " +
  "venue verge verse vicar video vigil villa vinyl viola viper viral virus visit visor vista " +
  "vital vivid vocal vodka vogue voice vomit voter vouch vowel wacky wafer wager wagon waist " +
  "waive waltz waste watch water waver waxen weary weave wedge weedy weigh weird whack whale " +
  "wharf wheat wheel whelp where which whiff while whine whirl whisk white whole whoop whose " +
  "widen wider widow width wield wince winch windy wiser witch witty woken woman women woody " +
  "world worry worse worst worth would wound woven wrack wrath wreak wreck wrest wring wrist " +
  "write wrong wrote wrung yacht yearn yeast yield young yours youth zebra zesty zonal";

export const WORDS = [...new Set(RAW.split(/\s+/).filter((w) => /^[a-z]{5}$/.test(w)))];
